# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 639be140e73c04182e298472d414af16e5a4876ab16c9a4ec35697ecda31118e5b469d5be31d311e53cb9d3161b67f7fa8910358c2a81c8b32dc3b8dc389b38e

test:
  secret_key_base: b4e6139e984ff602bd0032314669c274e22927c1e9aa88b1673f5acafe26e22701cf28babf15cf070edd9fdb754027f9b5e3507c118e5802c3d1b3ddccde9600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
